
/**
 * <p>This package contains event definitions shared between client and server.
 * Events are generated by the server and delivered to clients where they
 * are forwarded to classes that subscribed them.</p>
 * 
 * <p>New event classes are created by extending <code>MooshakEvent</code>
 * and make sure they provide a public constructor with no arguments.
 * Currently implemented events are:</p>
 * 
 * <ul>
 * 	<li><code>NotificationEvent</code> - Notification to specific
 * 		recipient, to be delivered in an alert box (for instance);</li>
 *  <li><code>ListingUpdate</code> - abstract class of all listing update 
 *  	events,sent to all registered recipients in a contest;</li>
 * 	<li><code>SubmissionsUpdate</code> - Record to add to submission listings;</li>
 * <li><code>RankingUpdate</code> - Record to add to ranking listings;</li>
 *  <li><code>PendingUpdate</code> - Record to add to pending listings;</li> 
 *  <li><code>QuestionsUpdate</code> - Record to add to questions listings;</li> 
 *  <li><code>PrintoutsUpdate</code> - Record to add to printouts listings;</li> 
 *  <li><code>BalloonsUpdate</code> - Record to add to balloons listings.</li> 
 * </ul>
 * 
 * <p>Classes needing to subscribe these events must implement 
 * <code>MooshakEventListener&lt; extends MooshakEventT&gt;</code>.  
 * 
 * @author José Paulo Leal <zp.dcc.fc.up.pt>
 */
package pt.up.fc.dcc.mooshak.shared.events;