//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 02:04:13 PM WEST 
//


package pt.up.fc.dcc.mooshak.content.erl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.up.fc.dcc.mooshak.content.erl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Message_QNAME = new QName("http://evae/messages", "message");
    private final static QName _Report_QNAME = new QName("http://evae/messages", "report");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.up.fc.dcc.mooshak.content.erl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link SummaryType.Feedback }
     * 
     */
    public SummaryType.Feedback createSummaryTypeFeedback() {
        return new SummaryType.Feedback();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link OutputDifferencesType }
     * 
     */
    public OutputDifferencesType createOutputDifferencesType() {
        return new OutputDifferencesType();
    }

    /**
     * Create an instance of {@link UserDataType }
     * 
     */
    public UserDataType createUserDataType() {
        return new UserDataType();
    }

    /**
     * Create an instance of {@link EnvironmentValueType }
     * 
     */
    public EnvironmentValueType createEnvironmentValueType() {
        return new EnvironmentValueType();
    }

    /**
     * Create an instance of {@link ExerciseType }
     * 
     */
    public ExerciseType createExerciseType() {
        return new ExerciseType();
    }

    /**
     * Create an instance of {@link TokenType }
     * 
     */
    public TokenType createTokenType() {
        return new TokenType();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link UserValueType }
     * 
     */
    public UserValueType createUserValueType() {
        return new UserValueType();
    }

    /**
     * Create an instance of {@link EnvironmentValuesType }
     * 
     */
    public EnvironmentValuesType createEnvironmentValuesType() {
        return new EnvironmentValuesType();
    }

    /**
     * Create an instance of {@link TestsType }
     * 
     */
    public TestsType createTestsType() {
        return new TestsType();
    }

    /**
     * Create an instance of {@link MarkType }
     * 
     */
    public MarkType createMarkType() {
        return new MarkType();
    }

    /**
     * Create an instance of {@link CapabilitiesType }
     * 
     */
    public CapabilitiesType createCapabilitiesType() {
        return new CapabilitiesType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ReplyType }
     * 
     */
    public ReplyType createReplyType() {
        return new ReplyType();
    }

    /**
     * Create an instance of {@link TestType }
     * 
     */
    public TestType createTestType() {
        return new TestType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link CapabilityType }
     * 
     */
    public CapabilityType createCapabilityType() {
        return new CapabilityType();
    }

    /**
     * Create an instance of {@link SummaryType.Feedback.Item }
     * 
     */
    public SummaryType.Feedback.Item createSummaryTypeFeedbackItem() {
        return new SummaryType.Feedback.Item();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://evae/messages", name = "message")
    public JAXBElement<MessageType> createMessage(MessageType value) {
        return new JAXBElement<MessageType>(_Message_QNAME, MessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://evae/messages", name = "report")
    public JAXBElement<ReportType> createReport(ReportType value) {
        return new JAXBElement<ReportType>(_Report_QNAME, ReportType.class, null, value);
    }

}
