//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 02:04:13 PM WEST 
//


package pt.up.fc.dcc.mooshak.content.erl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="input" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expectedOutput" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="obtainedOutput" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outputDifferences" type="{http://evae/messages}OutputDifferencesType"/>
 *         &lt;element name="classify" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mark" type="{http://evae/messages}MarkType"/>
 *         &lt;element name="feedback" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="environmentValues" type="{http://evae/messages}EnvironmentValuesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration label="file"/>
 *             &lt;enumeration label="group"/>
 *             &lt;enumeration label="description"/>
 *             &lt;enumeration label="generator"/>
 *             &lt;enumeration label="program"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="executionTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestType", propOrder = {
    "input",
    "expectedOutput",
    "obtainedOutput",
    "outputDifferences",
    "classify",
    "mark",
    "feedback",
    "environmentValues"
})
public class TestType {

    @XmlElement(required = true)
    protected String input;
    @XmlElement(required = true)
    protected String expectedOutput;
    @XmlElement(required = true)
    protected String obtainedOutput;
    @XmlElement(required = true)
    protected OutputDifferencesType outputDifferences;
    @XmlElement(required = true)
    protected String classify;
    @XmlElement(required = true)
    protected MarkType mark;
    @XmlElement(required = true)
    protected String feedback;
    @XmlElement(required = true)
    protected EnvironmentValuesType environmentValues;
	@XmlAttribute(name = "id")
	protected String id;
    @XmlAttribute(name = "mode")
    protected String mode;
    @XmlAttribute(name = "executionTime")
    protected Integer executionTime;

    /**
     * Gets the label of the input property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInput() {
        return input;
    }

    /**
     * Sets the label of the input property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInput(String value) {
        this.input = value;
    }

    /**
     * Gets the label of the expectedOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectedOutput() {
        return expectedOutput;
    }

    /**
     * Sets the label of the expectedOutput property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectedOutput(String value) {
        this.expectedOutput = value;
    }

    /**
     * Gets the label of the obtainedOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObtainedOutput() {
        return obtainedOutput;
    }

    /**
     * Sets the label of the obtainedOutput property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObtainedOutput(String value) {
        this.obtainedOutput = value;
    }

    /**
     * Gets the label of the outputDifferences property.
     * 
     * @return
     *     possible object is
     *     {@link OutputDifferencesType }
     *     
     */
    public OutputDifferencesType getOutputDifferences() {
        return outputDifferences;
    }

    /**
     * Sets the label of the outputDifferences property.
     * 
     * @param label
     *     allowed object is
     *     {@link OutputDifferencesType }
     *     
     */
    public void setOutputDifferences(OutputDifferencesType value) {
        this.outputDifferences = value;
    }

    /**
     * Gets the label of the classify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassify() {
        return classify;
    }

    /**
     * Sets the label of the classify property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassify(String value) {
        this.classify = value;
    }

    /**
     * Gets the label of the mark property.
     * 
     * @return
     *     possible object is
     *     {@link MarkType }
     *     
     */
    public MarkType getMark() {
        return mark;
    }

    /**
     * Sets the label of the mark property.
     * 
     * @param label
     *     allowed object is
     *     {@link MarkType }
     *     
     */
    public void setMark(MarkType value) {
        this.mark = value;
    }

    /**
     * Gets the label of the feedback property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * Sets the label of the feedback property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeedback(String value) {
        this.feedback = value;
    }

    /**
     * Gets the label of the environmentValues property.
     * 
     * @return
     *     possible object is
     *     {@link EnvironmentValuesType }
     *     
     */
    public EnvironmentValuesType getEnvironmentValues() {
        return environmentValues;
    }

    /**
     * Sets the label of the environmentValues property.
     * 
     * @param label
     *     allowed object is
     *     {@link EnvironmentValuesType }
     *     
     */
    public void setEnvironmentValues(EnvironmentValuesType value) {
        this.environmentValues = value;
    }

    /**
     * Gets the label of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the label of the mode property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the label of the executionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExecutionTime() {
        return executionTime;
    }

    /**
     * Sets the label of the executionTime property.
     * 
     * @param label
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExecutionTime(Integer value) {
        this.executionTime = value;
    }

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

    
}
