//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 02:04:13 PM WEST 
//


package pt.up.fc.dcc.mooshak.content.erl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for MarkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://evae/messages}MarkAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarkType", propOrder = {
    "content"
})
public class MarkType {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "totalValue")
    protected String totalValue;
    @XmlAttribute(name = "obtainedValue")
    protected String obtainedValue;

    /**
     * Gets the label of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the label of the content property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the label of the totalValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalValue() {
        return totalValue;
    }

    /**
     * Sets the label of the totalValue property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalValue(String value) {
        this.totalValue = value;
    }

    /**
     * Gets the label of the obtainedValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObtainedValue() {
        return obtainedValue;
    }

    /**
     * Sets the label of the obtainedValue property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObtainedValue(String value) {
        this.obtainedValue = value;
    }

}
