//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 02:04:13 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://evae/messages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pt.up.fc.dcc.mooshak.content.erl;
