//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 02:04:13 PM WEST 
//


package pt.up.fc.dcc.mooshak.content.erl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capability" type="{http://evae/messages}CapabilityType"/>
 *         &lt;element name="programmingLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="exercise" type="{http://evae/messages}ExerciseType"/>
 *         &lt;element name="compilationErrors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tests" type="{http://evae/messages}TestsType" minOccurs="0"/>
 *         &lt;element name="summary" type="{http://evae/messages}SummaryType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://evae/messages}DateAttributeGroup"/>
 *       &lt;attribute name="evaluationServer" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportType", propOrder = {
    "capability",
    "programmingLanguage",
    "exercise",
    "compilationErrors",
    "tests",
    "summary"
})
public class ReportType {

    @XmlElement(required = true)
    protected CapabilityType capability;
    protected String programmingLanguage;
    @XmlElement(required = true)
    protected ExerciseType exercise;
    protected String compilationErrors;
    protected TestsType tests;
    protected SummaryType summary;
    @XmlAttribute(name = "evaluationServer")
    @XmlSchemaType(name = "anyURI")
    protected String evaluationServer;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;

    /**
     * Gets the label of the capability property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityType }
     *     
     */
    public CapabilityType getCapability() {
        return capability;
    }

    /**
     * Sets the label of the capability property.
     * 
     * @param label
     *     allowed object is
     *     {@link CapabilityType }
     *     
     */
    public void setCapability(CapabilityType value) {
        this.capability = value;
    }

    /**
     * Gets the label of the programmingLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgrammingLanguage() {
        return programmingLanguage;
    }

    /**
     * Sets the label of the programmingLanguage property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgrammingLanguage(String value) {
        this.programmingLanguage = value;
    }

    /**
     * Gets the label of the exercise property.
     * 
     * @return
     *     possible object is
     *     {@link ExerciseType }
     *     
     */
    public ExerciseType getExercise() {
        return exercise;
    }

    /**
     * Sets the label of the exercise property.
     * 
     * @param label
     *     allowed object is
     *     {@link ExerciseType }
     *     
     */
    public void setExercise(ExerciseType value) {
        this.exercise = value;
    }

    /**
     * Gets the label of the compilationErrors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompilationErrors() {
        return compilationErrors;
    }

    /**
     * Sets the label of the compilationErrors property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompilationErrors(String value) {
        this.compilationErrors = value;
    }

    /**
     * Gets the label of the tests property.
     * 
     * @return
     *     possible object is
     *     {@link TestsType }
     *     
     */
    public TestsType getTests() {
        return tests;
    }

    /**
     * Sets the label of the tests property.
     * 
     * @param label
     *     allowed object is
     *     {@link TestsType }
     *     
     */
    public void setTests(TestsType value) {
        this.tests = value;
    }

    /**
     * Gets the label of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryType }
     *     
     */
    public SummaryType getSummary() {
        return summary;
    }

    /**
     * Sets the label of the summary property.
     * 
     * @param label
     *     allowed object is
     *     {@link SummaryType }
     *     
     */
    public void setSummary(SummaryType value) {
        this.summary = value;
    }

    /**
     * Gets the label of the evaluationServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvaluationServer() {
        return evaluationServer;
    }

    /**
     * Sets the label of the evaluationServer property.
     * 
     * @param label
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvaluationServer(String value) {
        this.evaluationServer = value;
    }

    /**
     * Gets the label of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the label of the date property.
     * 
     * @param label
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

}
