//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.19 at 11:31:31 AM WEST 
//


package pt.up.fc.dcc.eshu.client.eshugwt.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for Connects complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Connects">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connect" type="{http://www.example.org/EshuConfig}Connect" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Connects", propOrder = {
    "connect"
})
public class Connects {

    @XmlElement(required = true)
    protected List<Connect> connect;

    /**
     * Gets the value of the connect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Connect }
     * 
     * 
     */
    public List<Connect> getConnect() {
        if (connect == null) {
            connect = new ArrayList<Connect>();
        }
        return this.connect;
    }
    
    @Override
	public String toString() {
		return  this.connect.toString();
	}
    
	public boolean isConnectionValid(String with, String to){
		for(Connect connect : this.connect)
			if(connect.isConnectionValid(with, to))
			return true;
		return false;
	}

	public boolean isConnectionValid(String with, int value){
		
		for(Connect connect : this.connect){
			if(connect.isConnectionValid( with, value)){
			
			return true;
			}
		}
		return false;
	}

}
