//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.19 at 11:31:31 AM WEST 
//


package pt.up.fc.dcc.eshu.client.eshugwt.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EdgeStyle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EdgeStyle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headSource" type="{http://www.example.org/EshuConfig}Head_Edge"/>
 *         &lt;element name="headTarget" type="{http://www.example.org/EshuConfig}Head_Edge"/>
 *         &lt;element name="stereotype" type="{http://www.example.org/EshuConfig}Stereotype" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="iconTollbarSVGPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lineDuple" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="lineDash" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EdgeStyle", propOrder = {
    "headSource",
    "headTarget",
    "stereotype"
})
public class EdgeStyle {

    @XmlElement(required = true)
    protected HeadEdge headSource;
    @XmlElement(required = true)
    protected HeadEdge headTarget;
    protected Stereotype stereotype;
    @XmlAttribute(name = "iconTollbarSVGPath", required = true)
    protected String iconTollbarSVGPath;
    @XmlAttribute(name = "lineDuple", required = true)
    protected boolean lineDuple;
    @XmlAttribute(name = "lineDash", required = true)
    protected boolean lineDash;

    /**
     * Gets the value of the headSource property.
     * 
     * @return
     *     possible object is
     *     {@link HeadEdge }
     *     
     */
    public HeadEdge getHeadSource() {
        return headSource;
    }

    /**
     * Sets the value of the headSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadEdge }
     *     
     */
    public void setHeadSource(HeadEdge value) {
        this.headSource = value;
    }

    /**
     * Gets the value of the headTarget property.
     * 
     * @return
     *     possible object is
     *     {@link HeadEdge }
     *     
     */
    public HeadEdge getHeadTarget() {
        return headTarget;
    }

    /**
     * Sets the value of the headTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadEdge }
     *     
     */
    public void setHeadTarget(HeadEdge value) {
        this.headTarget = value;
    }

    /**
     * Gets the value of the stereotype property.
     * 
     * @return
     *     possible object is
     *     {@link Stereotype }
     *     
     */
    public Stereotype getStereotype() {
        return stereotype;
    }

    /**
     * Sets the value of the stereotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stereotype }
     *     
     */
    public void setStereotype(Stereotype value) {
        this.stereotype = value;
    }

    /**
     * Gets the value of the iconTollbarSVGPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconTollbarSVGPath() {
        return iconTollbarSVGPath;
    }

    /**
     * Sets the value of the iconTollbarSVGPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconTollbarSVGPath(String value) {
        this.iconTollbarSVGPath = value;
    }

    /**
     * Gets the value of the lineDuple property.
     * 
     */
    public boolean isLineDuple() {
        return lineDuple;
    }

    /**
     * Sets the value of the lineDuple property.
     * 
     */
    public void setLineDuple(boolean value) {
        this.lineDuple = value;
    }

    /**
     * Gets the value of the lineDash property.
     * 
     */
    public boolean isLineDash() {
        return lineDash;
    }

    /**
     * Sets the value of the lineDash property.
     * 
     */
    public void setLineDash(boolean value) {
        this.lineDash = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
    
	@Override
	public String toString() {
		return "{\"headSource\" :" + headSource + ", \"headTarget\" :" + "\""+headTarget + "\"" + ", \"stereotype\":" 
				+ "\"" +stereotype + "\"" + ", \"iconTollbarSVGPath\":" + "\"" + iconTollbarSVGPath + "\""
				+ ", \"lineDuple\":" + "\"" +lineDuple +"\"" + ", \"lineDash\" :" + "\"" + lineDash + "\""+  "}";
	}
	
}
