//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.19 at 11:31:31 AM WEST 
//


package pt.up.fc.dcc.eshu.client.eshugwt.jaxb;

import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Editor_style complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Editor_style">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="borderWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="borderColor" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="background" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gridVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="gridColorLine" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Editor_style")
public class EditorStyle {

    @XmlAttribute(name = "width", required = true)
    protected BigInteger width;
    @XmlAttribute(name = "height", required = true)
    protected BigInteger height;
    @XmlAttribute(name = "borderWidth", required = true)
    protected BigInteger borderWidth;
    @XmlAttribute(name = "borderColor", required = true)
    protected String borderColor;
    @XmlAttribute(name = "background", required = true)
    protected String background;
    @XmlAttribute(name = "gridVisible", required = true)
    protected boolean gridVisible;
    @XmlAttribute(name = "gridColorLine", required = true)
    protected String gridColorLine;

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the borderWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBorderWidth() {
        return borderWidth;
    }

    /**
     * Sets the value of the borderWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBorderWidth(BigInteger value) {
        this.borderWidth = value;
    }

    /**
     * Gets the value of the borderColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderColor() {
        return borderColor;
    }

    /**
     * Sets the value of the borderColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderColor(String value) {
        this.borderColor = value;
    }

    /**
     * Gets the value of the background property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackground(String value) {
        this.background = value;
    }

    /**
     * Gets the value of the gridVisible property.
     * 
     */
    public boolean isGridVisible() {
        return gridVisible;
    }

    /**
     * Sets the value of the gridVisible property.
     * 
     */
    public void setGridVisible(boolean value) {
        this.gridVisible = value;
    }

    /**
     * Gets the value of the gridColorLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridColorLine() {
        return gridColorLine;
    }

    /**
     * Sets the value of the gridColorLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridColorLine(String value) {
        this.gridColorLine = value;
    }
    
    public Map<String, String>  getInfo(){
    	
    	Map<String, String> list = new HashMap<String, String>();
    	list.put("width", this.width.toString());
    	list.put("height", this.height.toString());
    	list.put("borderWidth", this.borderWidth.toString());
    	list.put("borderColor", this.borderColor);
    	list.put("background",this.background );
    	list.put("gridVisible", booleamToString(this.gridVisible));
    	list.put("gridColorLine", this.gridColorLine);
    	
    	return list;
    	
    }

	private String booleamToString(boolean value){
		if(value)
			return "true";
		return "false";
	}

}
