//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.19 at 11:31:31 AM WEST 
//


package pt.up.fc.dcc.eshu.client.eshugwt.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeValidation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeValidation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connects" type="{http://www.example.org/EshuConfig}Connects"/>
 *       &lt;/sequence>
 *       &lt;attribute name="notAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="degreeIn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="degreeOut" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="allAnchorsConnect" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeValidation", propOrder = {
    "connects"
})
public class NodeValidation {

    @XmlElement(required = true)
    protected Connects connects;
    @XmlAttribute(name = "notAvailable")
    protected Boolean notAvailable;
    @XmlAttribute(name = "degreeIn", required = true)
    protected String degreeIn;
    @XmlAttribute(name = "degreeOut", required = true)
    protected String degreeOut;
    @XmlAttribute(name = "allAnchorsConnect", required = true)
    protected boolean allAnchorsConnect;

    /**
     * Gets the value of the connects property.
     * 
     * @return
     *     possible object is
     *     {@link Connects }
     *     
     */
    public Connects getConnects() {
        return connects;
    }

    /**
     * Sets the value of the connects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connects }
     *     
     */
    public void setConnects(Connects value) {
        this.connects = value;
    }

    /**
     * Gets the value of the notAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNotAvailable() {
        return notAvailable;
    }

    /**
     * Sets the value of the notAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotAvailable(Boolean value) {
        this.notAvailable = value;
    }

    /**
     * Gets the value of the degreeIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeIn() {
        return degreeIn;
    }

    /**
     * Sets the value of the degreeIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeIn(String value) {
        this.degreeIn = value;
    }

    /**
     * Gets the value of the degreeOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeOut() {
        return degreeOut;
    }

    /**
     * Sets the value of the degreeOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeOut(String value) {
        this.degreeOut = value;
    }

    /**
     * Gets the value of the allAnchorsConnect property.
     * 
     */
    public boolean isAllAnchorsConnect() {
        return allAnchorsConnect;
    }

    /**
     * Sets the value of the allAnchorsConnect property.
     * 
     */
    public void setAllAnchorsConnect(boolean value) {
        this.allAnchorsConnect = value;
    }
  
   
    @Override
   	public String toString() {
   		return "{\"connects\" :" + connects + ", \"notAvailable\" :" + "\""+notAvailable + "\"" + ", \"degreeIn\":" 
   				+ "\"" +this.getDegreeInInt() + "\"" + ", \"degreeOut\":" + "\"" + this.getDegreeOutInt() + "\""
   				+ ", \"allAnchorsConnect\":" + "\"" +allAnchorsConnect +  "}";
   	}
    
    
public boolean isDegreeValid(int in, int out){
		
		if(getDegreeInInt()>=in && getDegreeOutInt() >=out )
			return true;
		return false;
	}
	
	
	 public int getDegreeInInt(){
	    	if (this.degreeIn.equals("unbounded")) return Integer.MAX_VALUE; 
	    	return Integer.parseInt(this.degreeIn);
	    }
	    
	    public int getDegreeOutInt(){
	    	if (this.degreeOut.equals("unbounded")) return Integer.MAX_VALUE; 
	    	return Integer.parseInt(this.degreeOut);
	    }
	
	
    

}
