//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.19 at 11:31:31 AM WEST 
//


package pt.up.fc.dcc.eshu.client.eshugwt.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeStyle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeStyle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="autoresize" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="multiElement" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="iconTollbarSVGPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="imgSVGPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="roundCorner" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeStyle")
public class NodeStyle {

    @XmlAttribute(name = "autoresize", required = true)
    protected boolean autoresize;
    @XmlAttribute(name = "multiElement")
    protected Boolean multiElement;
    @XmlAttribute(name = "width", required = true)
    protected BigInteger width;
    @XmlAttribute(name = "height", required = true)
    protected BigInteger height;
    @XmlAttribute(name = "iconTollbarSVGPath", required = true)
    protected String iconTollbarSVGPath;
    @XmlAttribute(name = "imgSVGPath", required = true)
    protected String imgSVGPath;
    @XmlAttribute(name = "roundCorner")
    protected Integer roundCorner;

    /**
     * Gets the value of the autoresize property.
     * 
     */
    public boolean isAutoresize() {
        return autoresize;
    }

    /**
     * Sets the value of the autoresize property.
     * 
     */
    public void setAutoresize(boolean value) {
        this.autoresize = value;
    }

    /**
     * Gets the value of the multiElement property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultiElement() {
        return multiElement;
    }

    /**
     * Sets the value of the multiElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiElement(Boolean value) {
        this.multiElement = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the iconTollbarSVGPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconTollbarSVGPath() {
        return iconTollbarSVGPath;
    }

    /**
     * Sets the value of the iconTollbarSVGPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconTollbarSVGPath(String value) {
        this.iconTollbarSVGPath = value;
    }

    /**
     * Gets the value of the imgSVGPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgSVGPath() {
        return imgSVGPath;
    }

    /**
     * Sets the value of the imgSVGPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgSVGPath(String value) {
        this.imgSVGPath = value;
    }

    /**
     * Gets the value of the roundCorner property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRoundCorner() {
        return roundCorner;
    }

    /**
     * Sets the value of the roundCorner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRoundCorner(Integer value) {
        this.roundCorner = value;
    }
    
    @Override
	public String toString() {
		return "{\"autoresize\" :" + autoresize + ", \"multiElement\" :" + "\""+multiElement + "\"" + ", \"width\":" 
				+ "\"" +width + "\"" + ", \"height\":" + "\"" + height + "\""
				+ ", \"iconTollbarSVGPath\":" + "\"" +iconTollbarSVGPath +"\"" + ", \"imgSVGPath\" :" + "\"" + imgSVGPath + "\"" 
				+ ", \"roundCorner\" :" + "\"" + roundCorner + "\""+  "}";
	}
	
    
    
}
