//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.19 at 11:31:31 AM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/EshuConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pt.up.fc.dcc.eshu.client.eshugwt.jaxb;
