//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.19 at 11:31:31 AM WEST 
//


package pt.up.fc.dcc.eshu.client.eshugwt.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Style complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Style">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="editorStyle" type="{http://www.example.org/EshuConfig}Editor_style"/>
 *         &lt;element name="toolbarStyle" type="{http://www.example.org/EshuConfig}Toolbar_style"/>
 *         &lt;element name="windowsProperties" type="{http://www.example.org/EshuConfig}WindowsProperties"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Style", propOrder = {

})
public class Style {

    @XmlElement(required = true)
    protected EditorStyle editorStyle;
    @XmlElement(required = true)
    protected ToolbarStyle toolbarStyle;
    @XmlElement(required = true)
    protected WindowsProperties windowsProperties;
    
    
    

    /**
     * Gets the value of the editorStyle property.
     * 
     * @return
     *     possible object is
     *     {@link EditorStyle }
     *     
     */
    public EditorStyle getEditorStyle() {
        return editorStyle;
    }

    /**
     * Sets the value of the editorStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditorStyle }
     *     
     */
    public void setEditorStyle(EditorStyle value) {
        this.editorStyle = value;
    }

    /**
     * Gets the value of the toolbarStyle property.
     * 
     * @return
     *     possible object is
     *     {@link ToolbarStyle }
     *     
     */
    public ToolbarStyle getToolbarStyle() {
        return toolbarStyle;
    }

    /**
     * Sets the value of the toolbarStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolbarStyle }
     *     
     */
    public void setToolbarStyle(ToolbarStyle value) {
        this.toolbarStyle = value;
    }

    /**
     * Gets the value of the windowsProperties property.
     * 
     * @return
     *     possible object is
     *     {@link WindowsProperties }
     *     
     */
    public WindowsProperties getWindowsProperties() {
        return windowsProperties;
    }

    /**
     * Sets the value of the windowsProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowsProperties }
     *     
     */
    public void setWindowsProperties(WindowsProperties value) {
        this.windowsProperties = value;
    }
    

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "[\"editorStyle \":" + editorStyle.getInfo() + ", \"toolbarStyle\": " + ", \"textBox\" :" +  "]";
	}

}
