function authentication(){var Q='bootstrap',R='begin',S='gwt.codesvr.authentication=',T='gwt.codesvr=',U='authentication',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='Failed to load ',qb='head',rb='meta',sb='name',tb='authentication::',ub='::',vb='gwt:property',wb='content',xb='=',yb='gwt:onPropertyErrorFn',zb='Bad handler "',Ab='" for "gwt:onPropertyErrorFn"',Bb='gwt:onLoadErrorFn',Cb='" for "gwt:onLoadErrorFn"',Db='#',Eb='?',Fb='/',Gb='img',Hb='clear.cache.gif',Ib='baseUrl',Jb='authentication.nocache.js',Kb='base',Lb='//',Mb='locale',Nb='default',Ob='locale=',Pb=7,Qb='&',Rb='__gwt_Locale',Sb='_',Tb='Unexpected exception in locale detection, using default: ',Ub=2,Vb=3,Wb='user.agent',Xb='webkit',Yb='safari',Zb='msie',$b=10,_b=11,ac='ie10',bc=9,cc='ie9',dc=8,ec='ie8',fc='gecko',gc='gecko1_8',hc=4,ic='selectingPermutation',jc='authentication.devmode.js',kc='23EF2546196555B070C359412B978FC6',lc='2C40EFFDB3ECD3478BFD6C815AAFD34F',mc='37E1CCDD0BB80BEDAE800F75D85B3A85',nc='arb',oc='37E851D3C4086F3D427108BBE7E1155F',pc='es',qc='463E112980537F2DD9264C4FDCE23B0B',rc='pt',sc='4683255EC1B9B9EF8A84D24024FF3815',tc='4A856F65E432E65287F266932E1526AE',uc='53D8D85AD06EFED4372C1D5F0948E49A',vc='656ED9BA69F5F9B0E6B3F2DD145FCF62',wc='7D380BF48B279C9D3503795006D74DD6',xc='8832048BC8A14AB2DE87333A5B631041',yc='91446ED995B75A8702E78670E84F310B',zc='A6C4109CEFE3492AE16BEDEE65ADD880',Ac='AF68219DC72DD6C2053DE40DB2757735',Bc='C7E71F8AFC21A515B43B8EC77086F72D',Cc='D9DD8099EE418E5551F6DA6ADDB6310B',Dc='DC93BCE0AEE4B9D15F80FD0AA7DD9F72',Ec='DFA61109C2C50CBC34842FB493C64206',Fc='EE5CAFC4E9F79737ACD565146C3D78BF',Gc='FD8C0541132DD61A200A0680CD38B578',Hc=':',Ic='.cache.js',Jc='link',Kc='rel',Lc='stylesheet',Mc='href',Nc='loadExternalRefs',Oc='gwt/clean/clean.css',Pc='end',Qc='http:',Rc='file:',Sc='_gwt_dummy_',Tc='__gwtDevModeHook:authentication',Uc='Ignoring non-whitelisted Dev Mode URL: ',Vc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
authentication.__sendStats=t;authentication.__moduleName=U;authentication.__errFn=null;authentication.__moduleBase=W;authentication.__softPermutationId=X;authentication.__computePropValue=null;authentication.__getPropMap=null;authentication.__installRunAsyncCode=function(){};authentication.__gwtStartLoadingFragment=function(){return null};authentication.__gwt_isKnownPropertyValue=function(){return false};authentication.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};authentication.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[authentication.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
authentication.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(authentication.__errFn){n.onerror=function(){authentication.__errFn(U,new Error(pb+code))}}r.getElementsByTagName(qb)[X].appendChild(n)}
authentication.__startLoadingFragment=function(a){return G(a)};authentication.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(rb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(sb),k;if(j){j=j.replace(tb,db);if(j.indexOf(ub)>=X){continue}if(j==vb){k=i.getAttribute(wb);if(k){var l,m=k.indexOf(xb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==yb){k=i.getAttribute(wb);if(k){try{d=eval(k)}catch(a){alert(zb+k+Ab)}}}else if(j==Bb){k=i.getAttribute(wb);if(k){try{e=eval(k)}catch(a){alert(zb+k+Cb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;authentication.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Db);if(b==-1){b=a.length}var c=a.indexOf(Eb);if(c==-1){c=a.length}var d=a.lastIndexOf(Fb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Gb);b.src=a+Hb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Ib);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Jb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Kb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Lb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return authentication.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=X){var f=d.substring(e+Pb);var g=d.indexOf(Qb,e);if(g<X){g=d.length}b=d.substring(e+Pb,g)}}if(!b){b=__gwt_getMetaProperty(Mb)}if(!b){b=q[Rb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Mb,b)){var h=b.lastIndexOf(Sb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Tb+a)}q[Rb]=c;return b||Nb};l[Mb]={'arb':X,'default':Y,'es':Ub,'pt':Vb};m[Wb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Xb)!=-1}())return Yb;if(function(){return a.indexOf(Zb)!=-1&&(b>=$b&&b<_b)}())return ac;if(function(){return a.indexOf(Zb)!=-1&&(b>=bc&&b<_b)}())return cc;if(function(){return a.indexOf(Zb)!=-1&&(b>=dc&&b<_b)}())return ec;if(function(){return a.indexOf(fc)!=-1||b>=_b}())return gc;return db};l[Wb]={'gecko1_8':X,'ie10':Y,'ie8':Ub,'ie9':Vb,'safari':hc};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};authentication.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};authentication.__computePropValue=n;q.__gwt_activeModules[U].bindings=authentication.__getPropMap;t(Q,ic);if(s()){return G(jc)}var o;try{k([Nb,Yb],kc);k([Nb,gc],lc);k([Nb,cc],mc);k([nc,cc],oc);k([pc,gc],qc);k([rc,cc],sc);k([pc,cc],tc);k([Nb,ec],uc);k([nc,ec],vc);k([pc,ec],wc);k([nc,gc],xc);k([nc,ac],yc);k([rc,gc],zc);k([rc,ec],Ac);k([pc,Yb],Bc);k([rc,ac],Cc);k([rc,Yb],Dc);k([pc,ac],Ec);k([Nb,ac],Fc);k([nc,Yb],Gc);o=i[n(Mb)][n(Wb)];var p=o.indexOf(Hc);if(p!=-1){j=parseInt(o.substring(p+Y),$b);o=o.substring(X,p)}}catch(a){}authentication.__softPermutationId=j;return G(o+Ic)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Jc);b.setAttribute(Kc,Lc);b.setAttribute(Mc,G(a));r.getElementsByTagName(qb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Nc,R);c(Oc);t(Nc,Pc)}
D();authentication.__moduleBase=F();v[U].moduleBase=authentication.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Qc||q.location.protocol==Rc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Sc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Tc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Uc+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+Vc]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(qb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Pc);C(J);return true}
authentication.succeeded=authentication();